window.RESCENE_NEWS=[
 {slug:'love-attack-inkigayo-realtime-first',date:'2026.07.12',category:'notice',label:'RECORD',title:'「LOVE ATTACK」がSBS「人気歌謡」リアルタイム投票1位を獲得',text:'2026年7月12日放送のSBS「人気歌謡」で、「LOVE ATTACK」がリアルタイム投票1位を獲得しました。RESCENEにとって、音楽番組のリアルタイム投票1位は今回が初めてです。',image:'assets/mv/love-attack.jpg',sourceLink:'https://x.com/higher_twt/status/2076211910865994220?s=46',sourceLabel:'HIGHER公式Xで記事を見る'},
 {slug:'melon-top100-first-number-one',date:'2026.07.08',category:'notice',label:'MELON RECORD',title:'RESCENEがMelon TOP100で初の1位を記録',text:'2026年7月8日22時、RESCENEがMelon TOP100でグループ初となる1位を記録しました。記録達成時のYouTubeライブもあわせてご覧いただけます。',image:'assets/mv/pretty-girl.jpg',sourceLink:'https://www.youtube.com/live/v6n4XQdX6_8?si=trciEexVgiGpYX3C',sourceLabel:'記録達成時のYouTubeライブを見る'},
 {slug:'pretty-girl-melon-entry',date:'2026.07.08',category:'release',label:'PRETTY GIRL',title:'「Pretty Girl」がリリース1時間でMelon TOP100 22位にランクイン',text:'7月8日にリリースされたSpecial Single「Pretty Girl」は、リリース1時間後にMelon TOP100 22位にランクイン。その後、最高4位を記録しました。',image:'assets/mv/pretty-girl.jpg',sourceLink:'discography.html#special-single',sourceLabel:'ディスコグラフィを見る'},
 {slug:'goyang-ambassador',date:'2026.07.02',category:'ambassador',label:'AMBASSADOR',title:'京畿道 高陽市 広報大使に任命',text:'メイの故郷・高陽市の広報大使にRESCENEが任命されました。',image:'assets/members/may.jpg',sourceLink:'https://m.entertain.naver.com/home/article/079/0004164566',sourceLabel:'記事を見る'},
 {slug:'gyeongju-ambassador',date:'2026.06.29',category:'ambassador',label:'AMBASSADOR',title:'慶尚北道 慶州市 広報大使に任命',text:'ゼナの故郷・慶州市の観光広報大使にRESCENEが任命されました。',image:'assets/members/zena.jpg',sourceLink:'https://m.entertain.naver.com/home/article/311/0002027805',sourceLabel:'記事を見る'},
 {slug:'suwon-ambassador',date:'2026.06.24',category:'ambassador',label:'AMBASSADOR',title:'京畿道 水原市 広報大使に任命',text:'リブの故郷・水原市の広報大使にRESCENEが任命されました。',image:'assets/members/liv.jpg',sourceLink:'https://m.entertain.naver.com/home/article/408/0000312710',sourceLabel:'記事を見る'},
 {slug:'geoje-ambassador',date:'2026.05.22',category:'ambassador',label:'AMBASSADOR',title:'慶尚南道 巨済市 広報大使に任命',text:'ウォニの故郷・巨済市の広報大使にRESCENEが任命されました。',image:'assets/members/woni.jpg',sourceLink:'https://n.news.naver.com/article/030/0003430663?sid=103',sourceLabel:'記事を見る'},
 {slug:'runaway-release',date:'2026.04.08',category:'release',label:'RELEASE',title:'Digital Single「Runaway」',text:'デジタルシングル「Runaway」の作品情報と配信リンクを掲載しています。',image:'assets/mv/runaway.jpg',sourceLink:'discography.html#special-single',sourceLabel:'作品情報を見る'},
 {slug:'second-anniversary',date:'2026.03.26',category:'notice',label:'ANNIVERSARY',title:'RESCENE Debut 2nd Anniversary',text:'デビュー2周年を迎えたRESCENEを日本から一緒にお祝いします。',image:'assets/group/rescene-group.jpg',sourceLink:'about.html',sourceLabel:'RESCENEについて見る'},
 {slug:'second-anniversary-project',date:'2026.03',category:'event',label:'PROJECT',title:'デビュー2周年広告プロジェクト',text:'日本・韓国で実施した2周年広告プロジェクトのお知らせです。',image:'assets/group/rescene-group.jpg',sourceLink:'news.html',sourceLabel:'ニュース一覧へ戻る'},
 {slug:'lip-bomb-release',date:'2025',category:'release',label:'MINI ALBUM',title:'3rd Mini Album「lip bomb」',text:'balm ver. / tint ver. の作品情報を掲載しています。',image:'assets/mv/bloom.jpg',sourceLink:'discography.html#mini-album',sourceLabel:'作品情報を見る'},
 {slug:'fanbase-site',date:'UPDATE',category:'notice',label:'NOTICE',title:'RESCENE JAPAN FANBASE ウェブサイト',text:'日本のREMINEに必要な情報をまとめるサイトを準備しています。',image:'assets/group/rescene-group.jpg',sourceLink:'about.html',sourceLabel:'サイトについて見る'}
];
