/* generated by scripts/generate-pwa.py */
const CACHE_NAME="rescene-pwa-ef102875ce63";
const CORE=["/", "/index.html", "/offline.html", "/schedule.html", "/news.html", "/discography.html", "/mv.html", "/records.html", "/music-show-wins.html", "/melon-records.html", "/korean-charts.html", "/streaming.html", "/voting.html", "/chants.html", "/members.html", "/links.html", "/fan-services.html", "/favorites.html", "/search.html", "/css/common.css", "/css/home-latest.css", "/css/search.css", "/css/notion-theme.css", "/css/korean-charts.css", "/js/common.js", "/js/i18n.js", "/js/site-content.js", "/js/schedule.js", "/js/melon-records.js", "/js/korean-charts.js", "/js/image-optimizer.js", "/manifest.webmanifest", "/assets/icons/app-icon-192.png", "/assets/icons/app-icon-512.png", "/data/homepage.json", "/data/homepage-data.js", "/data/language-catalog.json", "/data/language-catalog-data.js", "/data/news.json", "/data/schedule.json", "/data/schedule-data.js", "/data/members.json", "/data/discography.json", "/data/chants.json", "/data/voting-guide.json", "/data/mv.json", "/data/records.json", "/data/korean-charts.json", "/data/korean-charts-data.js"];
const isFreshContent=url=>url.pathname.startsWith("/data/")||url.pathname==="/css/notion-theme.css"||url.pathname==="/css/korean-charts.css"||url.pathname==="/js/korean-charts.js"||/\/assets\/[^/]+\/notion\//.test(url.pathname);
self.addEventListener("install",event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting()));});
self.addEventListener("activate",event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith("rescene-pwa-")&&key!==CACHE_NAME).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));});
self.addEventListener("message",event=>{if(event.data==="SKIP_WAITING")self.skipWaiting();});
self.addEventListener("fetch",event=>{
  const request=event.request;if(request.method!=="GET")return;
  const url=new URL(request.url);if(url.origin!==location.origin)return;
  if(request.mode==="navigate"){event.respondWith(fetch(request).then(response=>{const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy));return response;}).catch(async()=>await caches.match(request)||await caches.match("/offline.html")));return;}
  // Dynamic data and the Korean chart renderer must always check the network
  // first, otherwise a previous PWA cache can keep an old graph implementation.
  if(isFreshContent(url)){event.respondWith(fetch(request,{cache:"no-store"}).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy));}return response;}).catch(async()=>await caches.match(request)));return;}
  event.respondWith(caches.match(request).then(cached=>{const network=fetch(request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(request,copy));}return response;}).catch(()=>cached);return cached||network;}));
});
